version: '2'

services:
  exam_prep:
     build:
       context: .
     ports:
       - "8000-8081"
     volumes:
       - ./exam_prep:/exam_prep
     command: >
       sh -c "python manage.py runserver 0.0.0.0:8081"
     environment:
       - DB_HOST=db1
       - DB_NAME=exam_prep_db
       - DB_USER=postgres
       - DB_PASS=password
     depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=exam_prep_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
